const ContentActionTypes = {
    FETCH_CONTENT_START: 'FETCH_CONTENT_START',
    FETCH_CONTENT_SUCCESS: 'FETCH_CONTENT_SUCCESS',
    FETCH_CONTENT_FAILURE: 'FETCH_CONTENT_FAILURE'
  };
  
  export default ContentActionTypes;